version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8118:80"
    volumes:
      - server-data:/app/data
    restart: unless-stopped

volumes:
  server-data:
